---
title: "Untitled"
author: "Devin Khosla"
date: "11/27/2019"
output: pdf_document
---

```{r setup, include=FALSE,echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(tidyverse)
require(doParallel)
require(foreach)
require(tm)
require(lubridate)
require(stringr)
```

# Reading in Data

```{r,echo=FALSE,message=FALSE}
filenames <- dir("data17/")
filenames <- paste0("data17/",filenames)

citi17 <- foreach(month = 1:12, .combine = 'rbind') %dopar% {
  file <- filenames[month]
  this.data <- readr::read_csv(file)
  colnames(this.data) <- removePunctuation(tolower(colnames(this.data)))
  colnames(this.data) <- str_replace_all(colnames(this.data), fixed(" "), "")
  this.data
}

filenames <- dir("data18/")
filenames <- paste0("data18/",filenames)

citi18 <- foreach(month = 1:12, .combine = 'rbind') %dopar% {
  file <- filenames[month]
  this.data <- readr::read_csv(file)
  colnames(this.data) <- removePunctuation(tolower(colnames(this.data)))
  colnames(this.data) <- str_replace_all(colnames(this.data), fixed(" "), "")
  this.data
}

stops <- read_csv("data/citibike_locations.csv")
names(stops)[1:2] <- c("station", "capacity")

rm(this.data,file,filenames,month)
```

# Remove columns we will not need

```{r}
citi17 <- citi17 %>% select(-bikeid,-birthyear,-gender)
citi18 <- citi18 %>% select(-bikeid,-birthyear,-gender)
```

# Cleaning Data

```{r}
citi17 <- citi17 %>% 
  filter(citi17$startstationname %in% stops$station & citi17$endstationname %in% stops$station)
citi18 <- citi18 %>% 
  filter(citi18$startstationname %in% stops$station & citi18$endstationname %in% stops$station)
```

```{r}
citi17 <- citi17 %>% filter(tripduration < 2700)
citi18 <- citi18 %>% filter(tripduration < 2700)
```

```{r}
citi17$start_date <- as.Date(citi17$starttime, format = "%m/%d/$Y")
citi17$start_hour <- lubridate::hour(citi17$starttime)

citi17$end_date <- as.Date(citi17$stoptime, format = "%m/$d/$Y")
citi17$end_hour <- lubridate::hour(citi17$stoptime)
```

```{r}
station_start <- citi17 %>%
  group_by(startstationname, start_date, start_hour) %>%
  summarize(start_count = n())
names(station_start)[1:3] <- c("station", "date", "hour")

station_end <- citi17 %>%
  group_by(endstationname, end_date, end_hour) %>%
  summarize(end_count = n()) 

names(station_end)[1:3] <- c("station", "date", "hour")
```

```{r}
stations1 <- data.frame(station = citi17$startstationname,date = citi17$start_date) %>% 
  distinct()
stations2 <- data.frame(station = citi17$endstationname,date = citi17$end_date) %>% 
  distinct()
stations <- rbind(stations1,stations2) %>% 
  distinct()

stations <- stations %>% crossing(hour = 0:23)

rm(stations1,stations2)

# Identifying capacity and how many bikes 
station_capacity <- stations %>% 
  left_join(station_start, by = c("station", "date", "hour")) %>% 
  left_join(station_end,by = c("station", "date", "hour")) %>% 
  mutate(start_count = replace_na(start_count, 0),
         end_count = replace_na(end_count, 0)) %>% 
  left_join(stops, by = "station") %>%
  mutate(bikes_available = capacity - start_count + end_count,
         percent_capacity = bikes_available/capacity)
```

```{r}
stations_closed <- stations %>% 
  select(station,date) %>% 
  distinct() %>% 
  group_by(station) %>%
  arrange(date, .by_group = T) %>% 
  mutate(diffs = date - lag(date)) %>%
  filter(diffs > 7) 
```

```{r}
lat_longs <- citi17 %>% 
  select(startstationname,startstationlatitude,startstationlongitude) %>%
  distinct()

res1 <- RANN::nn2((lat_longs[,2:3]),k = nrow(lat_longs),searchtype = "radius",radius = (0.5/111))
distances <- res1$nn.dists
distances <- distances < 0.05
radius_count <- rowSums(distances) - 1

stops$radius_count <- ifelse(stops$station %in% lat_longs$startstationname,radius_count,NA)

rm(lat_longs,res1,distances,radius_count)
```

```{r}
# snow and rain everyday of the 2017 and 2018 
weather <- readr::read_csv("data/weather_full.csv")
names(weather["Precopitation"]) <- "Precipitation"
weather <- weather %>% 
  mutate(trace.snow = ifelse(Snow.Depth == "T" | New.Snow == "T", 1, 0),
         trace.rain = ifelse(Precipitation == "T", 1, 0),
         Snow.Depth = as.numeric(ifelse(Snow.Depth == "T", 0, Snow.Depth)),
         New.Snow = as.numeric(ifelse(New.Snow == "T", 0, New.Snow)),
         Precipitation = as.numeric(ifelse(Precipitation == "T", 0, Precipitation)),
         date = lubridate::date(lubridate::mdy(Date)))
```

```{r}
Holidays17 <- date(c("2017-01-01","2017-01-16","2017-02-20","2017-05-29","2017-07-04","2017-09-04",
                     "2019-10-09","2017-11-10","2017-11-23","2017-11-24","2017-12-25"))

Holidays18 <- date(c("2017-01-01","2017-01-15","2017-02-19","2017-05-28","2017-07-04","2017-09-03",
                     "2019-10-08","2017-11-12","2017-11-22","2017-11-23","2017-12-25"))
```

```{r}
##Summary by day 
stations_day <- stations[,-3]
stations_day <- unique(stations_day)

station_start_day <- station_start %>%
                      ungroup() %>%
                      group_by(station, date) %>%
                      arrange(date, .by_group=T) %>%
                      summarize(start_day = sum(start_count))

colnames(station_start_day) <- c("station","date", "start_day")

station_end_day <- station_end %>%
                      ungroup() %>%
                      group_by(station, date) %>%
                      arrange(date, .by_group=T) %>%
                      summarize(end_day = sum(end_count))

colnames(station_end_day) <- c("station","date", "end_day")

stations_day <- stations_day %>% filter(!(station %in% stations_closed))

stations_day <- left_join(stations_day, station_start_day, by = c("station","date"))
stations_day <- left_join(stations_day, station_end_day, by = c("station","date"))
stations_day <- left_join(stations_day, stops, by = "station")

stations_day$start_day <- ifelse(is.na(stations_day$start_day), 0, stations_day$start_day)
stations_day$end_day <- ifelse(is.na(stations_day$end_day),0, stations_day$end_day)
stations_day$percent <- (stations_day$end_day - stations_day$start_day)/stations_day$capacity

stations_day$outcome <- ifelse(stations_day$percent > .25 | stations_day$percent < -.25, 1, 0)
stations_day$weekday <- as.factor(weekdays(stations_day$date))
stations_day$month <-as.factor(month(stations_day$date))
stations_day$holiday <- ifelse(stations_day$date %in% Holidays17,1, 0)

full_data <- left_join(stations_day, weather, by = "date")
full_data <- full_data %>% select(-Date, -Departure, -HDD, -CDD)

```

